UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup", 
        "swan", 
        "harp", 
        "squirrel", 
        "snail", 
        "ray", 
        "pineapple", 
        "volcano", 
        "rifle", 
        "scissors", 
        "parrot", 
        "windmill", 
        "teddy_bear", 
        "tree", 
        "wine_bottle", 
        "deer", 
        "chicken", 
        "airplane", 
        "wheelchair", 
        "tank", 
        "umbrella", 
        "butterfly", 
        "camel", 
        "horse", 
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    # "quickdraw": [
    #     "alarm_clock",
    #     "axe",
    #     "bandage",
    #     "bat",
    #     "beach",
    #     "bread",
    #     "bus",
    #     "cake",
    #     "campfire",
    #     "cruise ship",
    #     "dolphin",
    #     "eiffel tower",
    #     "eyeglasses",
    #     "fire_hydrant",
    #     "flower",
    #     "giraffe",
    #     "hamburger",
    #     "helicopter",
    #     "hot-air_balloon",
    #     "kangaroo",
    #     "map",
    #     "megaphone",
    #     "moon",
    #     "motorcycle",
    #     "palm tree",
    #     "parrot",
    #     "raccoon",
    #     "sailboat",
    #     "skyscraper",
    #     "windmill",
    # ],

    "quickdraw": [
        "bat",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "skyscraper",
        "tree",
        "windmill",
        "feather",
        "campfire",
        "palm tree",
        "fire_hydrant",
        "bread",
        "beach",
        "megaphone",
        "cactus",
        "zebra",
        "tiger",
        "shark",
        "frog",
        "banana",
        "cake",
        "hamburger",
        "fan",
    ],

    # "tuberlin": [
    #     "airplane",
    #     "alarm clock",
    #     "angel",
    #     "ant",
    #     "apple",
    #     "armchair",
    #     "axe",
    #     "backpack",
    #     "barn",
    #     "tennis-racket",
    #     "bathtub",
    #     "bear (animal)",
    #     "bee",
    #     "beer-mug",
    #     "bell",
    #     "bicycle",
    #     "binoculars",
    #     "blimp",
    #     "bottle opener",
    #     "brain",
    #     "bus",
    #     "cactus",
    #     "calculator",
    #     "camel",
    #     "canoe",
    #     "car (sedan)",
    #     "castle",
    #     "chandelier",
    #     "cigarette",
    #     "computer monitor",
    # ],
    
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "airplane",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "cup",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "bus",
        "tv",
    ],
}

GENERALIZED_CLASSES = {
    "sketchy_2": {
        "teapot",
        "harp",
        "piano",
        "trumpet",
        "saxophone",
        "hourglass",
        "mushroom",
        "pretzel",
        "bell"
    },
    
    "tuberlin": {
        "airplane",
        "blimp",
        "tablelamp",
        "telephone",
        "human-skeleton",
        "pickup truck"
    }
}

VISUALIZE_CLASSES = {
    "sketchy_2": [
        "cow",
        "raccoon",
        "scissors",
        "seagull",
        "sword",
        "tree",
    ],
}
